PURGE RECYCLEBIN;
DROP TABLE REPRODUCCIO CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE LLISTA_CONTINGUT CASCADE CONSTRAINTS;
DROP TABLE LLISTA CASCADE CONSTRAINTS;
DROP TABLE ALBUM_CONTINGUT CASCADE CONSTRAINTS;
DROP TABLE ALBUM CASCADE CONSTRAINTS;
DROP TABLE AUTORIA CASCADE CONSTRAINTS;
DROP TABLE CANCO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTE CASCADE CONSTRAINTS;
DROP TABLE H_GRUP CASCADE CONSTRAINTS;
DROP TABLE ART_IND CASCADE CONSTRAINTS;
DROP TABLE ART_GRUP CASCADE CONSTRAINTS;
DROP TABLE ARTISTA CASCADE CONSTRAINTS;
DROP TABLE ESTIL CASCADE CONSTRAINTS;
DROP TABLE PAIS CASCADE CONSTRAINTS;
PURGE RECYCLEBIN;

CREATE TABLE PAIS ( -- GOOD
  pais_iso CHAR(3),
  pais_nom VARCHAR2(250) NOT NULL,
  CONSTRAINT pk_pais_iso PRIMARY KEY (pais_iso),
  CONSTRAINT un_pais_nom UNIQUE (pais_nom)
);

CREATE TABLE ESTIL ( -- GOOD
  estil_id NUMBER(5) GENERATED ALWAYS AS IDENTITY,
  estil_nom VARCHAR2(69) NOT NULL,
  CONSTRAINT pk_estil_id PRIMARY KEY (estil_id),
  CONSTRAINT un_estil_nom UNIQUE (estil_nom)
);

CREATE TABLE ARTISTA ( -- GOOD
  artista_id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
  artista_nom VARCHAR2(69) NOT NULL,
  artista_tipus CHAR(1) NOT NULL,
  CONSTRAINT pk_artista_id PRIMARY KEY (artista_id),
  CONSTRAINT un_artista_nom UNIQUE (artista_nom),
  CONSTRAINT ck_artista_tipus CHECK (artista_tipus IN ('I', 'G'))
);

CREATE TABLE ART_GRUP ( -- GOOD
  grup_id NUMBER(5),
  grup_data_creacio DATE NOT NULL,
  CONSTRAINT pk_artista_grup PRIMARY KEY (grup_id),
  CONSTRAINT fk_artista_grup_artista FOREIGN KEY (grup_id) REFERENCES ARTISTA (artista_id)
);

CREATE TABLE ART_IND ( -- GOOD
  -- ind
  ind_id NUMBER(5),
  ind_data_naixement DATE NOT NULL,
  ind_nacionalitat CHAR(3) NOT NULL,
  CONSTRAINT pk_artista_individual PRIMARY KEY (ind_id),
  CONSTRAINT fk_artista_individual_artista FOREIGN KEY (ind_id) REFERENCES ARTISTA (artista_id),
  CONSTRAINT fk_artista_individual_pais FOREIGN KEY (ind_nacionalitat) REFERENCES PAIS (pais_iso)
);

CREATE TABLE H_GRUP ( -- GOOD
  hgrup_id_art_grup NUMBER(5),
  hgrup_id_art_ind NUMBER(5),

  hgrup_data_inici DATE,
  hgrup_data_fi DATE,

  CONSTRAINT pk_h_grup PRIMARY KEY (hgrup_id_art_grup, hgrup_id_art_ind),
  CONSTRAINT fk_h_grup_artista_grup FOREIGN KEY (hgrup_id_art_grup) REFERENCES ART_GRUP (grup_id),
  CONSTRAINT fk_h_grup_artista_individual FOREIGN KEY (hgrup_id_art_ind) REFERENCES ART_IND (ind_id),
  CONSTRAINT chk_h_grup_data_fi CHECK (hgrup_data_fi > hgrup_data_inici)
);

CREATE TABLE PRODUCTE ( -- GOOD
  producte_id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
  producte_titol VARCHAR2(250) NOT NULL,
  producte_actiu CHAR(1) NOT NULL,
  producte_estil NUMBER(5) NOT NULL,
  producte_tipus CHAR(1) NOT NULL,

  CONSTRAINT pk_producte_id PRIMARY KEY (producte_id),
  CONSTRAINT fk_producte_estil FOREIGN KEY (producte_estil) REFERENCES ESTIL (estil_id),
  CONSTRAINT ck_producte_actiu CHECK (producte_actiu IN ('S', 'N')),
  CONSTRAINT ck_producte_tipus CHECK (producte_tipus IN ('C','A','L'))
);

CREATE INDEX idx_producte_titol ON PRODUCTE (producte_titol); -- GOOD

CREATE TABLE CANCO ( -- GOOD
  canco_id NUMBER(5),
  canco_any_creacio INT NOT NULL,
  canco_interpet NUMBER(5),
  canco_durada INT NOT NULL,

  CONSTRAINT pk_canco_id PRIMARY KEY (canco_id),
  CONSTRAINT fk_canco_artista FOREIGN KEY (canco_interpet) REFERENCES ARTISTA (artista_id),
  CONSTRAINT fk_canco_producte FOREIGN KEY (canco_id) REFERENCES PRODUCTE (producte_id),
  CONSTRAINT ck_canco_durada CHECK (canco_durada > 0)
);

CREATE TABLE AUTORIA ( -- GOOD
  autoria_id_canco NUMBER(5),
  autoria_id_art_ind NUMBER(5),

  CONSTRAINT pk_autoria PRIMARY KEY (autoria_id_canco, autoria_id_art_ind),
  CONSTRAINT fk_autoria_canco FOREIGN KEY (autoria_id_canco) REFERENCES CANCO (canco_id),
  CONSTRAINT fk_autoria_ind FOREIGN KEY (autoria_id_art_ind) REFERENCES ART_IND (ind_id)
);

CREATE TABLE ALBUM ( -- GOOD
  album_id NUMBER(5),
  album_any_creacio INT NOT NULL,
  album_durada INT NOT NULL,

  CONSTRAINT pk_album_id PRIMARY KEY (album_id),
  CONSTRAINT fk_album_producte FOREIGN KEY (album_id) REFERENCES PRODUCTE (producte_id),
  CONSTRAINT ck_album_durada CHECK (album_durada >= 0)
);

CREATE TABLE ALBUM_CONTINGUT ( -- GOOD
  -- album_con
  album_con_id_album NUMBER(5),
  album_con_id_canco NUMBER(5),
  album_con_posicio NUMBER(5) NOT NULL,

  CONSTRAINT pk_album_contingut PRIMARY KEY (album_con_id_album, album_con_id_canco),
  CONSTRAINT fk_album_contingut_album FOREIGN KEY (album_con_id_album) REFERENCES ALBUM (album_id),
  CONSTRAINT fk_album_con_id_canco FOREIGN KEY (album_con_id_canco) REFERENCES PRODUCTE (producte_id),
  
  CONSTRAINT un_album_contingut_posicio UNIQUE (album_con_id_album, album_con_posicio),
  CONSTRAINT ck_album_contingut_posicio CHECK (album_con_posicio > 0)
);

CREATE TABLE LLISTA ( -- GOOD
  llista_id NUMBER(5),
  llista_durada INT NOT NULL,

  CONSTRAINT pk_llista_id PRIMARY KEY (llista_id),
  CONSTRAINT fk_llista_producte FOREIGN KEY (llista_id) REFERENCES PRODUCTE (producte_id),
  CONSTRAINT ck_llista_durada CHECK (llista_durada >= 0)
);

CREATE TABLE LLISTA_CONTINGUT ( -- GOOD
  -- llista_con
  llista_con_id_llista NUMBER(5),
  llista_con_id_producte NUMBER(5),
  llista_con_posicio NUMBER(5) NOT NULL,

  CONSTRAINT pk_llista_contingut PRIMARY KEY (llista_con_id_llista, llista_con_id_producte),
  CONSTRAINT fk_llista_contingut_llista FOREIGN KEY (llista_con_id_llista) REFERENCES LLISTA (llista_id),
  CONSTRAINT fk_llista_con_id_producte FOREIGN KEY (llista_con_id_producte) REFERENCES PRODUCTE (producte_id),
  
  CONSTRAINT un_llista_contingut_posicio UNIQUE (llista_con_id_llista, llista_con_posicio),
  CONSTRAINT ck_llista_contingut_posicio CHECK (llista_con_posicio > 0)
);

CREATE TABLE CLIENT ( -- GOOD
  client_id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
  client_email VARCHAR2(100) NOT NULL,
  client_nom VARCHAR2(100) NOT NULL,
  client_cognoms VARCHAR2(100) NOT NULL,
  client_data_naixement DATE NOT NULL,

  client_codi_postal VARCHAR2(10) NOT NULL,
  client_domicili1 VARCHAR2(100) NOT NULL,
  client_domicili2 VARCHAR2(100),
  client_poblacio VARCHAR2(100) NOT NULL,
  client_pais CHAR(3) NOT NULL,

  CONSTRAINT pk_client_id PRIMARY KEY (client_id),
  CONSTRAINT fk_client_pais FOREIGN KEY (client_pais) REFERENCES PAIS (pais_iso),
  CONSTRAINT un_client_email UNIQUE (client_email)
);

CREATE INDEX index_client_cognoms_nom ON CLIENT (client_cognoms, client_nom); -- GOOD

CREATE TABLE REPRODUCCIO ( -- GOOD
  --rep
  rep_id_client NUMBER(5),  
  rep_moment_temporal DATE,
  rep_id_producte NUMBER(5) NOT NULL,

  CONSTRAINT pk_reproduccio PRIMARY KEY (rep_id_client, rep_moment_temporal),
  CONSTRAINT fk_reproduccio_client FOREIGN KEY (rep_id_client) REFERENCES CLIENT (client_id),
  CONSTRAINT fk_reproduccio_producte FOREIGN KEY (rep_id_producte) REFERENCES PRODUCTE (producte_id)
);
